# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pendaftaran.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(756, 487)
        Form.setAutoFillBackground(False)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(330, 30, 401, 21))
        self.label_8.setStyleSheet("\n"
"font: 87 18pt \"Source Sans Pro Black\";\n"
"color: rgb(227, 202, 165);\n"
"")
        self.label_8.setObjectName("label_8")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(330, 60, 391, 71))
        self.plainTextEdit.setStyleSheet("border: none;\n"
"font: 11pt \"Source Sans Pro\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"text-align: justify;\n"
"color:rgb(227, 202, 165);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(330, 180, 191, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color: rgb(227, 202, 165);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color: rgb(227, 202, 165);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color:rgb(227, 202, 165);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_4.addWidget(self.lineEdit_7)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 311, 491))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/images/download.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(330, 380, 321, 21))
        self.checkBox.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color: rgb(173, 139, 115);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(330, 400, 321, 21))
        self.checkBox_2.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color: rgb(173, 139, 115);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(330, 150, 121, 16))
        self.label_10.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color: rgb(149, 110, 75);\n"
"")
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(330, 430, 71, 31))
        self.pushButton.setStyleSheet("background-color: rgb(173, 139, 115);\n"
"color:rgb(255, 251, 233);\n"
"font: 80 10pt \"Source Sans Pro\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(440, 440, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 0, 631, 491))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/images/wallpaper.jpg"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(540, 180, 191, 181))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color: rgb(227, 202, 165);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color: rgb(227, 202, 165);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_5.addWidget(self.lineEdit_6)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_12.setStyleSheet("font: 63 9pt \"Source Sans Pro Semibold\";\n"
"color:rgb(227, 202, 165);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_5.addWidget(self.lineEdit_8)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 460, 151, 20))
        self.label_13.setStyleSheet("font: 63 9pt \"Source Sans Pro bold\";\n"
"color: rgb(227, 202, 165);\n"
"")
        self.label_13.setObjectName("label_13")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 150, 41, 16))
        self.pushButton_2.setStyleSheet("font: 90 9pt \"Source Sans Pro\";\n"
"border: no border;\n"
"color:rgb(56, 112, 168);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3.raise_()
        self.label_8.raise_()
        self.plainTextEdit.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.label_2.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.label_10.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.label_13.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "WELCOME TO DECOFFE MEMBERSHIP"))
        self.plainTextEdit.setPlainText(_translate("Form", "Ayo! daftarkan diri anda di Decoffe Membership untuk mendapatkan potongan harga serta promo - promo menarik lainnya"))
        self.label_4.setText(_translate("Form", "Nama Depan"))
        self.label_6.setText(_translate("Form", "Telepon"))
        self.label_9.setText(_translate("Form", "Kata Sandi"))
        self.checkBox.setText(_translate("Form", "Ya. saya ingin menerima email DeCoffe Membership"))
        self.checkBox_2.setText(_translate("Form", "Saya menyetujui persyaratan, kebijakan privasi, dan biaya"))
        self.label_10.setText(_translate("Form", "Sudah memiliki akun?"))
        self.pushButton.setText(_translate("Form", "Sign Up"))
        self.label_5.setText(_translate("Form", "Nama Belakang"))
        self.label_7.setText(_translate("Form", "E-Mail"))
        self.label_12.setText(_translate("Form", "Konfirmasi Kata Sandi"))
        self.label_13.setText(_translate("Form", "Developed by Diah Pitaloka"))
        self.pushButton_2.setText(_translate("Form", "Log in"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
